apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-master-config
data:
  postgresql.conf: |
    listen_addresses = '*'
    max_connections = 100
    shared_buffers = 128MB
    wal_level = replica
    max_wal_senders = 3
    max_replication_slots = 3
    wal_keep_size = 64MB
    hot_standby = on

  pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    local   all             all                                     trust
    host    all             all             127.0.0.1/32            trust
    host    all             all             ::1/128                 trust
    host    all             all             0.0.0.0/0               trust
    host    replication     replicator      0.0.0.0/0               trust
